import { CatalogueEnum, CatalogueDataType } from "src/types/Catalogue";

export const CatalogueLinks: Record<CatalogueEnum, string> = {
  [CatalogueEnum.Anarkali]: "/collections/anarkali",
  [CatalogueEnum.Kurta]: "/collections/kurta",
  [CatalogueEnum.Dress]: "/collections/dress",
  [CatalogueEnum.NewArrivals]: "/collections/new-arrivals",
};

export const CatalogueData: CatalogueDataType[] = [
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description:
      "A pleated Chanderi silhouette in cobalt blue, paired with a scalloped organza dupatta.Floral embroidery on the bodice adds delicate charm to this festive classic. Material Kurta: Chanderi Dupatta: Pure Organza Length - Top wear : 58 inches",
    imageUrl: [
      "https://i.ibb.co/BxtSLdG/image.webp",
      "https://i.ibb.co/8nCMqhFs/1.webp",
      "https://i.ibb.co/G4XD3XpS/2.webp",
    ],
    link: "/product/009",
    price: 28878,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Seher",
    description: "Shrouded in ancient mystery.",
    imageUrl: [
      "https://i.ibb.co/LDX7MVn0/image.webp",
      "https://i.ibb.co/WpsMmLjK/1.webp",
    ],
    link: "/product/002",
    price: 45278,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Seher",
    description: "Crafted from celestial matter.",
    imageUrl: [
      "https://i.ibb.co/LDX7MVn0/image.webp",
      "https://i.ibb.co/WpsMmLjK/1.webp",
    ],
    link: "/product/002",
    price: 22632,
    isNewArrival: true,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Elder Wand",
  //   description: "Passed down through generations.",
  //   imageUrl: [
  //     "http://1.bp.blogspot.com/-vtoGkVTLOkE/UvkUp83B3LI/AAAAAAAAP68/SJp1wiZ0tQw/s1600/sl1353.jpg",
  //     "https://1.bp.blogspot.com/-E2iQhmOeUww/UuKhArPPjSI/AAAAAAABBf8/2OzJ2Wrj9SE/s1600/Simple-Salwar-Kameez-6+www.Clothing9.blogspot.com.jpg",
  //   ],
  //   link: "/product/elder-wand-3",
  //   price: 3574,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 44342,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Kurta,
    title: "Eva",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/GvsZxfW5/image.webp",
      "https://i.ibb.co/mrhpQbBs/1.webp",
    ],
    link: "/product/004",
    price: 6360,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Moon Pendant",
  //   description: "Crafted from celestial matter.",
  //   imageUrl: [
  //     "http://static1.squarespace.com/static/5c832b55af4683b3a857c8ef/t/60de7f8e0b09d9394918eb68/1625194382545/Designer+Salwar+Suit.jpeg?format=1500w",
  //     "https://prathamwholesale.com/images/product/sub_images/2023/02/panghat-by-tulsi-fashion-special-summer-seasons-designer-salwar-kameez-catalogue-design-2023-2-2023-02-01_18_02_44.jpg",
  //   ],
  //   link: "/product/moon-pendant-6",
  //   price: 24390,
  //   isNewArrival: false,
  // },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Elder Wand",
  //   description: "Protects from dark magic.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/designer-salwar-kameez-resham-art-silk-in-navy-blue-151871.jpg",
  //     "https://www.kollybollyethnics.com/image/catalog/data/03Feb2020/Purple-georgette-churidar-salwar-kameez-7087.jpg",
  //   ],
  //   link: "/product/elder-wand-7",
  //   price: 13361,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "An item of great power.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 6421,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Its glow captivates the soul.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 42794,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Seher",
    description: "An item of great power.",
    imageUrl: [
      "https://i.ibb.co/1fphgkKn/image.webp",
      "https://i.ibb.co/RT5HGXDN/1.webp",
    ],
    link: "/product/008",
    price: 70058,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Invisible Cloak",
  //   description: "Crafted from celestial matter.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/invisible-cloak-11",
  //   price: 71026,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 37951,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Moon Pendant",
  //   description: "Protects from dark magic.",
  //   imageUrl: [
  //     "https://images.wholesalesalwar.com/2023y/April/40134/Pink-Malmal-Festival-Wear-Hand-Work-Readymade-Salwar-Suit-SG2268.jpg",
  //     "http://1.bp.blogspot.com/-jJoGNplECXE/UUMfVOOBE0I/AAAAAAABE6s/F01yevxb6k0/s1600/jacqueline-fernandez_Salwar_Suit_Photoshoot_004.jpg",
  //   ],
  //   link: "/product/moon-pendant-13",
  //   price: 45202,
  //   isNewArrival: true,
  // },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Elder Wand",
  //   description: "An item of great power.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/elder-wand-14",
  //   price: 42663,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.Kurta,
    title: "Moh",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/WWV54ZD2/image.webp",
      "https://i.ibb.co/pByGpg1v/1.webp",
    ],
    link: "/product/011",
    price: 55801,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Seher",
    description: "An item of great power.",
    imageUrl: [
      "https://i.ibb.co/1fphgkKn/image.webp",
      "https://i.ibb.co/RT5HGXDN/1.webp",
    ],
    link: "/product/008",
    price: 15314,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Elder Wand",
  //   description: "Brings luck to its holder.",
  //   imageUrl: [
  //     "http://static1.squarespace.com/static/5c832b55af4683b3a857c8ef/t/60de7f8e0b09d9394918eb68/1625194382545/Designer+Salwar+Suit.jpeg?format=1500w",
  //     "https://prathamwholesale.com/images/product/sub_images/2023/02/panghat-by-tulsi-fashion-special-summer-seasons-designer-salwar-kameez-catalogue-design-2023-2-2023-02-01_18_02_44.jpg",
  //   ],
  //   link: "/product/elder-wand-17",
  //   price: 10718,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/d4cKr8cf/image.webp",
      "https://i.ibb.co/PZHcLNjn/1.webp",
    ],
    link: "/product/007",
    price: 22682,
    isNewArrival: true,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Mystic Orb",
  //   description: "Crafted from celestial matter.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/mystic-orb-19",
  //   price: 15324,
  //   isNewArrival: true,
  // },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Starlight Crown",
  //   description: "Protects from dark magic.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/starlight-crown-20",
  //   price: 28898,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.Anarkali,
    title: "Seher",
    description: "An item of great power.",
    imageUrl: [
      "https://i.ibb.co/1fphgkKn/image.webp",
      "https://i.ibb.co/RT5HGXDN/1.webp",
    ],
    link: "/product/008",
    price: 40516,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Witch's Broom",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://royalanarkali.com/wp-content/uploads/2021/06/glorious-yellow-color-heavy-rayon-sequence-work-designer-salwar-suit-3-scaled.jpg",
      "https://cdn2.thebridalbox.com/wp-content/uploads/2016/09/Jacket-Styled-salwar-styles.jpg",
    ],
    link: "/product/witch's-broom-22",
    price: 18632,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Vampire Fang",
  //   description: "Once belonged to a famous wizard.",
  //   imageUrl: [
  //     "http://static1.squarespace.com/static/5c832b55af4683b3a857c8ef/t/60de7f8e0b09d9394918eb68/1625194382545/Designer+Salwar+Suit.jpeg?format=1500w",
  //     "https://prathamwholesale.com/images/product/sub_images/2023/02/panghat-by-tulsi-fashion-special-summer-seasons-designer-salwar-kameez-catalogue-design-2023-2-2023-02-01_18_02_44.jpg",
  //   ],
  //   link: "/product/vampire-fang-23",
  //   price: 22610,
  //   isNewArrival: false,
  // },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Sorcerer's Stone",
  //   description: "Its glow captivates the soul.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/sorcerer's-stone-24",
  //   price: 40291,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Kurta,
    title: "Moh",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/WWV54ZD2/image.webp",
      "https://i.ibb.co/pByGpg1v/1.webp",
    ],
    link: "/product/011",
    price: 16928,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Sorcerer's Stone",
  //   description: "Passed down through generations.",
  //   imageUrl: [
  //     "https://images.wholesalesalwar.com/2023y/April/40134/Pink-Malmal-Festival-Wear-Hand-Work-Readymade-Salwar-Suit-SG2268.jpg",
  //     "http://1.bp.blogspot.com/-jJoGNplECXE/UUMfVOOBE0I/AAAAAAABE6s/F01yevxb6k0/s1600/jacqueline-fernandez_Salwar_Suit_Photoshoot_004.jpg",
  //   ],
  //   link: "/product/sorcerer's-stone-26",
  //   price: 64176,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Anarkali,
    title: "Seher",
    description: "An item of great power.",
    imageUrl: [
      "https://i.ibb.co/1fphgkKn/image.webp",
      "https://i.ibb.co/RT5HGXDN/1.webp",
    ],
    link: "/product/008",
    price: 4178,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Invisible Cloak",
  //   description: "Infused with lunar essence.",
  //   imageUrl: [
  //     "https://royalanarkali.com/wp-content/uploads/2021/06/glorious-yellow-color-heavy-rayon-sequence-work-designer-salwar-suit-3-scaled.jpg",
  //     "https://cdn2.thebridalbox.com/wp-content/uploads/2016/09/Jacket-Styled-salwar-styles.jpg",
  //   ],
  //   link: "/product/invisible-cloak-28",
  //   price: 34867,
  //   isNewArrival: true,
  // },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/d4cKr8cf/image.webp",
      "https://i.ibb.co/PZHcLNjn/1.webp",
    ],
    link: "/product/007",
    price: 7647,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Mystic Orb",
  //   description: "Its glow captivates the soul.",
  //   imageUrl: [
  //     "http://1.bp.blogspot.com/-vtoGkVTLOkE/UvkUp83B3LI/AAAAAAAAP68/SJp1wiZ0tQw/s1600/sl1353.jpg",
  //     "https://1.bp.blogspot.com/-E2iQhmOeUww/UuKhArPPjSI/AAAAAAABBf8/2OzJ2Wrj9SE/s1600/Simple-Salwar-Kameez-6+www.Clothing9.blogspot.com.jpg",
  //   ],
  //   link: "/product/mystic-orb-30",
  //   price: 28882,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 40012,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description:
      "A pleated Chanderi silhouette in cobalt blue, paired with a scalloped organza dupatta.Floral embroidery on the bodice adds delicate charm to this festive classic. Material Kurta: Chanderi Dupatta: Pure Organza Length - Top wear : 58 inches",
    imageUrl: [
      "https://i.ibb.co/BxtSLdG/image.webp",
      "https://i.ibb.co/8nCMqhFs/1.webp",
      "https://i.ibb.co/G4XD3XpS/2.webp",
    ],
    link: "/product/009",
    price: 44989,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Goblin Coin",
  //   description: "Shrouded in ancient mystery.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/goblin-coin-33",
  //   price: 65657,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/d4cKr8cf/image.webp",
      "https://i.ibb.co/PZHcLNjn/1.webp",
    ],
    link: "/product/007",
    price: 71866,
    isNewArrival: true,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Moon Pendant",
  //   description: "Passed down through generations.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/embroidered-salwar-kameez-158992.jpg",
  //     "http://www.kollybollyethnics.com/image/catalog/data/31Aug2017/Sonal-chauhan-lavender-color-net-party-wear-anarkali-suit-4707.jpg",
  //   ],
  //   link: "/product/moon-pendant-35",
  //   price: 6803,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description:
      "A pleated Chanderi silhouette in cobalt blue, paired with a scalloped organza dupatta.Floral embroidery on the bodice adds delicate charm to this festive classic. Material Kurta: Chanderi Dupatta: Pure Organza Length - Top wear : 58 inches",
    imageUrl: [
      "https://i.ibb.co/BxtSLdG/image.webp",
      "https://i.ibb.co/8nCMqhFs/1.webp",
      "https://i.ibb.co/G4XD3XpS/2.webp",
    ],
    link: "/product/009",
    price: 72279,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Sorcerer's Stone",
  //   description: "An item of great power.",
  //   imageUrl: [
  //     "https://royalanarkali.com/wp-content/uploads/2021/06/glorious-yellow-color-heavy-rayon-sequence-work-designer-salwar-suit-3-scaled.jpg",
  //     "https://cdn2.thebridalbox.com/wp-content/uploads/2016/09/Jacket-Styled-salwar-styles.jpg",
  //   ],
  //   link: "/product/sorcerer's-stone-37",
  //   price: 13575,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/d4cKr8cf/image.webp",
      "https://i.ibb.co/PZHcLNjn/1.webp",
    ],
    link: "/product/007",
    price: 59579,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 58388,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 72853,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Kurta,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/jZJK3d3t/image.webp",
      "https://i.ibb.co/GvJZ12R9/1.webp",
    ],
    link: "/product/006",
    price: 46239,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Invisible Cloak",
  //   description: "Holds a secret only few know.",
  //   imageUrl: [
  //     "http://1.bp.blogspot.com/-vtoGkVTLOkE/UvkUp83B3LI/AAAAAAAAP68/SJp1wiZ0tQw/s1600/sl1353.jpg",
  //     "https://1.bp.blogspot.com/-E2iQhmOeUww/UuKhArPPjSI/AAAAAAABBf8/2OzJ2Wrj9SE/s1600/Simple-Salwar-Kameez-6+www.Clothing9.blogspot.com.jpg",
  //   ],
  //   link: "/product/invisible-cloak-42",
  //   price: 45967,
  //   isNewArrival: false,
  // },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Mystic Orb",
  //   description: "Passed down through generations.",
  //   imageUrl: [
  //     "https://cdn.sareeka.com/image/data2020/designer-salwar-kameez-resham-art-silk-in-navy-blue-151871.jpg",
  //     "https://www.kollybollyethnics.com/image/catalog/data/03Feb2020/Purple-georgette-churidar-salwar-kameez-7087.jpg",
  //   ],
  //   link: "/product/mystic-orb-43",
  //   price: 38081,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 73862,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Kurta,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/jZJK3d3t/image.webp",
      "https://i.ibb.co/GvJZ12R9/1.webp",
    ],
    link: "/product/006",
    price: 5776,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Kurta,
    title: "Moh",
    description: "Infused with lunar essence.",
    imageUrl: [
      "https://i.ibb.co/jZJK3d3t/image.webp",
      "https://i.ibb.co/GvJZ12R9/1.webp",
    ],
    link: "/product/006",
    price: 24611,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Seher",
    description: "Crafted from celestial matter.",
    imageUrl: [
      "https://i.ibb.co/LDX7MVn0/image.webp",
      "https://i.ibb.co/WpsMmLjK/1.webp",
    ],
    link: "/product/002",
    price: 73684,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Seher",
    description: "Crafted from celestial matter.",
    imageUrl: [
      "https://i.ibb.co/LDX7MVn0/image.webp",
      "https://i.ibb.co/WpsMmLjK/1.webp",
    ],
    link: "/product/002",
    price: 17727,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Invisible Cloak",
  //   description: "Holds a secret only few know.",
  //   imageUrl: [
  //     "http://static1.squarespace.com/static/5c832b55af4683b3a857c8ef/t/60de7f8e0b09d9394918eb68/1625194382545/Designer+Salwar+Suit.jpeg?format=1500w",
  //     "https://prathamwholesale.com/images/product/sub_images/2023/02/panghat-by-tulsi-fashion-special-summer-seasons-designer-salwar-kameez-catalogue-design-2023-2-2023-02-01_18_02_44.jpg",
  //   ],
  //   link: "/product/invisible-cloak-49",
  //   price: 11470,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description:
      "A pleated Chanderi silhouette in cobalt blue, paired with a scalloped organza dupatta.Floral embroidery on the bodice adds delicate charm to this festive classic. Material Kurta: Chanderi Dupatta: Pure Organza Length - Top wear : 58 inches",
    imageUrl: [
      "https://i.ibb.co/BxtSLdG/image.webp",
      "https://i.ibb.co/8nCMqhFs/1.webp",
      "https://i.ibb.co/G4XD3XpS/2.webp",
    ],
    link: "/product/009",
    price: 7334,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Anarkali,
    title: "Ruh",
    description: "Once belonged to a famous wizard.",
    imageUrl: [
      "https://i.ibb.co/RTyw7N56/image.webp",
      "https://i.ibb.co/Fkd2dB1j/1.webp",
    ],
    link: "/product/003",
    price: 49098,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 10019,
    isNewArrival: false,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 22633,
    isNewArrival: false,
  },
  // {
  //   id: Catalogue.VelvetAndTissueEdit,
  //   title: "Goblin Coin",
  //   description: "Brings luck to its holder.",
  //   imageUrl: [
  //     "http://1.bp.blogspot.com/-vtoGkVTLOkE/UvkUp83B3LI/AAAAAAAAP68/SJp1wiZ0tQw/s1600/sl1353.jpg",
  //     "https://1.bp.blogspot.com/-E2iQhmOeUww/UuKhArPPjSI/AAAAAAABBf8/2OzJ2Wrj9SE/s1600/Simple-Salwar-Kameez-6+www.Clothing9.blogspot.com.jpg",
  //   ],
  //   link: "/product/goblin-coin-54",
  //   price: 50476,
  //   isNewArrival: false,
  // },
  // {
  //   id: Catalogue.Bestsellers,
  //   title: "Vampire Fang",
  //   description: "Once belonged to a famous wizard.",
  //   imageUrl: [
  //     "http://1.bp.blogspot.com/-vtoGkVTLOkE/UvkUp83B3LI/AAAAAAAAP68/SJp1wiZ0tQw/s1600/sl1353.jpg",
  //     "https://1.bp.blogspot.com/-E2iQhmOeUww/UuKhArPPjSI/AAAAAAABBf8/2OzJ2Wrj9SE/s1600/Simple-Salwar-Kameez-6+www.Clothing9.blogspot.com.jpg",
  //   ],
  //   link: "/product/vampire-fang-55",
  //   price: 29506,
  //   isNewArrival: false,
  // },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 28569,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 15629,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.Dress,
    title: "Nyah",
    description: "Protects from dark magic.",
    imageUrl: [
      "https://i.ibb.co/jktzmCsR/image.webp",
      "https://i.ibb.co/x82njXjd/1.webp",
    ],
    link: "/product/010",
    price: 71467,
    isNewArrival: true,
  },
  {
    id: CatalogueEnum.NewArrivals,
    title: "Seher",
    description: "Crafted from celestial matter.",
    imageUrl: [
      "https://i.ibb.co/LDX7MVn0/image.webp",
      "https://i.ibb.co/WpsMmLjK/1.webp",
    ],
    link: "/product/002",
    price: 69736,
    isNewArrival: true,
  },
];
